# Generated by Django 5.1.5 on 2025-02-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='confirmuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='confirmuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='confirmuser',
            name='username',
        ),
        migrations.AddField(
            model_name='confirmuser',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='confirmuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_code', to='users.user'),
        ),
    ]
