# Generated by Django 5.1.5 on 2025-02-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_alter_confirmuser_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirmuser',
            name='code',
            field=models.CharField(default=1234, max_length=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
